openapi: 3.0.0
info:
  description: API para gestionar solicitudes académicas y su ciclo de vida.
  title: API Sistema de Triage Académico
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /api/solicitudes:
    get:
      operationId: listarSolicitudes
      parameters:
      - explode: true
        in: query
        name: estado
        required: false
        schema:
          $ref: '#/components/schemas/EstadoSolicitud'
        style: form
      - explode: true
        in: query
        name: tipo
        required: false
        schema:
          $ref: '#/components/schemas/TipoSolicitud'
        style: form
      - explode: true
        in: query
        name: prioridad
        required: false
        schema:
          $ref: '#/components/schemas/Prioridad'
        style: form
      - explode: true
        in: query
        name: responsableId
        required: false
        schema:
          format: int64
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SolicitudResponse'
                type: array
          description: Lista de solicitudes
      summary: Listar solicitudes con filtros
      x-accepts:
      - application/json
    post:
      operationId: registrarSolicitud
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SolicitudCreateRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SolicitudResponse'
          description: Solicitud creada correctamente
      summary: Registrar una nueva solicitud
      x-content-type: application/json
      x-accepts:
      - application/json
  /api/solicitudes/{id}:
    get:
      operationId: obtenerSolicitudPorId
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SolicitudResponse'
          description: Solicitud encontrada
        "404":
          description: Solicitud no encontrada
      summary: Obtener solicitud por id
      x-accepts:
      - application/json
  /api/solicitudes/{id}/clasificar:
    patch:
      operationId: clasificarSolicitud
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - explode: true
        in: query
        name: usuarioId
        required: true
        schema:
          format: int64
          type: integer
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClasificarSolicitudRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SolicitudResponse'
          description: Solicitud clasificada correctamente
        "409":
          description: Transición inválida
        "403":
          description: Usuario no autorizado
      summary: Clasificar una solicitud
      x-content-type: application/json
      x-accepts:
      - application/json
  /api/solicitudes/{id}/prioridad:
    put:
      operationId: asignarPrioridad
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - explode: true
        in: query
        name: usuarioId
        required: true
        schema:
          format: int64
          type: integer
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AsignarPrioridadRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SolicitudResponse'
          description: Prioridad asignada correctamente
        "403":
          description: Usuario no autorizado
      summary: Asignar prioridad a una solicitud
      x-content-type: application/json
      x-accepts:
      - application/json
  /api/solicitudes/{id}/asignar:
    patch:
      operationId: asignarResponsable
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - explode: true
        in: query
        name: usuarioId
        required: true
        schema:
          format: int64
          type: integer
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AsignarResponsableRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SolicitudResponse'
          description: Responsable asignado correctamente
        "403":
          description: Usuario no autorizado
      summary: Asignar responsable a una solicitud
      x-content-type: application/json
      x-accepts:
      - application/json
  /api/solicitudes/{id}/historial:
    get:
      operationId: obtenerHistorial
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/HistorialSolicitudResponse'
                type: array
          description: Historial encontrado
      summary: Obtener historial de una solicitud
      x-accepts:
      - application/json
  /api/solicitudes/{id}/estado:
    patch:
      operationId: cambiarEstado
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CambiarEstadoRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SolicitudResponse'
          description: Estado cambiado correctamente
        "409":
          description: Transición inválida
      summary: Cambiar el estado de una solicitud
      x-content-type: application/json
      x-accepts:
      - application/json
  /api/solicitudes/{id}/cerrar:
    put:
      operationId: cerrarSolicitud
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - explode: true
        in: query
        name: usuarioId
        required: true
        schema:
          format: int64
          type: integer
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CerrarSolicitudRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SolicitudResponse'
          description: Solicitud cerrada correctamente
        "403":
          description: Usuario no autorizado
      summary: Cerrar una solicitud
      x-content-type: application/json
      x-accepts:
      - application/json
  /api/solicitudes/{id}/resumen:
    get:
      operationId: generarResumen
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: Resumen generado correctamente
      summary: Generar resumen de una solicitud
      x-accepts:
      - text/plain
  /api/solicitudes/sugerir-clasificacion:
    post:
      operationId: sugerirClasificacion
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SugerirClasificacionRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SugerenciaClasificacionResponse'
          description: Sugerencia generada correctamente
      summary: Generar sugerencia automática de clasificación
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  schemas:
    SolicitudResponse:
      example:
        descripcion: descripcion
        tipo: REGISTRO_ASIGNATURAS
        estado: REGISTRADA
        canalOrigen: PRESENCIAL
        solicitanteId: 6
        observacionCierre: observacionCierre
        fechaRegistro: 2000-01-23T04:56:07.000+00:00
        justificacionPrioridad: justificacionPrioridad
        prioridad: BAJA
        impactoAcademico: BAJO
        responsableAsignadoId: 1
        fechaLimite: 2000-01-23
        historial:
        - accion: accion
          usuarioResponsableId: 5
          fechaHora: 2000-01-23T04:56:07.000+00:00
          observacion: observacion
        - accion: accion
          usuarioResponsableId: 5
          fechaHora: 2000-01-23T04:56:07.000+00:00
          observacion: observacion
        id: 0
      properties:
        id:
          format: int64
          type: integer
        tipo:
          $ref: '#/components/schemas/TipoSolicitud'
        descripcion:
          type: string
        canalOrigen:
          $ref: '#/components/schemas/CanalOrigen'
        fechaRegistro:
          format: date-time
          type: string
        solicitanteId:
          format: int64
          type: integer
        responsableAsignadoId:
          format: int64
          nullable: true
          type: integer
        estado:
          $ref: '#/components/schemas/EstadoSolicitud'
        prioridad:
          $ref: '#/components/schemas/Prioridad'
        justificacionPrioridad:
          nullable: true
          type: string
        impactoAcademico:
          $ref: '#/components/schemas/ImpactoAcademico'
        fechaLimite:
          format: date
          nullable: true
          type: string
        observacionCierre:
          nullable: true
          type: string
        historial:
          items:
            $ref: '#/components/schemas/HistorialSolicitudResponse'
          type: array
      type: object
    HistorialSolicitudResponse:
      example:
        accion: accion
        usuarioResponsableId: 5
        fechaHora: 2000-01-23T04:56:07.000+00:00
        observacion: observacion
      properties:
        fechaHora:
          format: date-time
          type: string
        accion:
          type: string
        observacion:
          type: string
        usuarioResponsableId:
          format: int64
          type: integer
      type: object
    SolicitudCreateRequest:
      example:
        descripcion: descripcion
        tipo: REGISTRO_ASIGNATURAS
        canalOrigen: PRESENCIAL
        solicitanteId: 0
      properties:
        tipo:
          $ref: '#/components/schemas/TipoSolicitud'
        descripcion:
          type: string
        canalOrigen:
          $ref: '#/components/schemas/CanalOrigen'
        solicitanteId:
          format: int64
          type: integer
      required:
      - canalOrigen
      - descripcion
      - solicitanteId
      - tipo
      type: object
    ClasificarSolicitudRequest:
      example:
        tipo: REGISTRO_ASIGNATURAS
      properties:
        tipo:
          $ref: '#/components/schemas/TipoSolicitud'
      required:
      - tipo
      type: object
    AsignarPrioridadRequest:
      example:
        fechaLimite: 2000-01-23
        impactoAcademico: BAJO
      properties:
        impactoAcademico:
          $ref: '#/components/schemas/ImpactoAcademico'
        fechaLimite:
          format: date
          type: string
      required:
      - fechaLimite
      - impactoAcademico
      type: object
    AsignarResponsableRequest:
      example:
        responsableId: 0
      properties:
        responsableId:
          format: int64
          type: integer
      required:
      - responsableId
      type: object
    CambiarEstadoRequest:
      example:
        nuevoEstado: REGISTRADA
        usuarioId: 0
        observacion: observacion
      properties:
        nuevoEstado:
          $ref: '#/components/schemas/EstadoSolicitud'
        observacion:
          type: string
        usuarioId:
          format: int64
          type: integer
      required:
      - nuevoEstado
      - usuarioId
      type: object
    CerrarSolicitudRequest:
      example:
        observacionCierre: observacionCierre
      properties:
        observacionCierre:
          type: string
      required:
      - observacionCierre
      type: object
    SugerirClasificacionRequest:
      example:
        descripcion: descripcion
      properties:
        descripcion:
          maxLength: 1000
          minLength: 10
          type: string
      required:
      - descripcion
      type: object
    SugerenciaClasificacionResponse:
      example:
        prioridadSugerida: BAJA
        justificacion: justificacion
        tipoSugerido: REGISTRO_ASIGNATURAS
      properties:
        tipoSugerido:
          $ref: '#/components/schemas/TipoSolicitud'
        prioridadSugerida:
          $ref: '#/components/schemas/Prioridad'
        justificacion:
          type: string
      type: object
    EstadoSolicitud:
      enum:
      - REGISTRADA
      - CLASIFICADA
      - EN_ATENCION
      - ATENDIDA
      - CERRADA
      type: string
    TipoSolicitud:
      enum:
      - REGISTRO_ASIGNATURAS
      - HOMOLOGACION
      - CANCELACION_ASIGNATURAS
      - SOLICITUD_CUPOS
      - CONSULTA_ACADEMICA
      type: string
    Prioridad:
      enum:
      - BAJA
      - MEDIA
      - ALTA
      - CRITICA
      type: string
    ImpactoAcademico:
      enum:
      - BAJO
      - MEDIO
      - ALTO
      type: string
    CanalOrigen:
      enum:
      - PRESENCIAL
      - CORREO
      - SAC
      - CSU
      - TELEFONICO
      type: string

